// export const SUCCESS = "SUCCESS"
// export const FAILURE = "FAILURE"
// export const LOADING = "LOADING"
// export const SINGLE_MOVIE = "SINGLE_MOVIE"
// export const MOVIES_SEARCH = "MOVIES_SEARCH"

export const SUCCESS = "SUCCESS"
export const FAILURE = "FAILURE"
export const LOADING = "LOADING"
export const SINGLE_USER = "SINGLE_USER"
export const USER_SEARCH = "USER_SEARCH"
